### ISSUE TITLE
score crashes when adding "Tutorial" process

### ISSUE THREAD

**Issue by thibaudk** [OSSIA/iscore-addon-tutorial#1]
tho both "Tutorial" and  "Tutorial QML" panels work fine.

tested with score commit https://github.com/OSSIA/score/commit/89aa62f6b4c9830948ea1f8a833f434eb3212d8a
on Ubuntu 17.10

**Comment by thibaudk** [comment]
commit e037878 
now compiles with score commit https://github.com/OSSIA/score/commit/539a6626f13f0b3db636ecd6492b2abab01b1327 
only if 
https://github.com/OSSIA/iscore-addon-tutorial/blob/master/score_addon_tutorial.hpp#L42
till line 49 are commented out

tested on Ubuntu 18.04

**Comment by jcelerier** [comment]
this has been fixed but not yet pushed sorry

**Comment by jcelerier** [comment]
works fine here now
